---
title: "learning-fay-herriot"
format: html
---

# Overview

The overall goal of this notebook is to begin tinkering with the Fay-Herriot model using only the ACS data. The package `emdi` seems to have functions for this. So I hope to gain some insight into how this all works by running code and tinkering with the relevant tools. 

## Imports

```{r}
library(emdi)
library(dplyr)
library(sf)
```

## Data Ingestion and Processing

```{r}
acs_df <- sf::st_read("../data/acs/2023_5_year_acs.shp") %>%
    mutate(variance = sd^2) %>%
    filter(var_name == "agriculture_industry")
head(acs_df)
```

```{r}
plot(
    acs_df %>%
    select(var_name, est, sd, geometry) %>%
    filter(var_name == "agriculture_industry") %>%
    select(-"var_name")
)
```

## Modeling

```{r}
# fh wants a pure dataframe. For the simplest FH model we don't care about the spatial aspect anyway.
simple_df <- sf::st_drop_geometry(acs_df)

fh_simple <- emdi::fh(
    fixed = est ~ 1,
    vardir = "variance",
    combined_data=simple_df,
    correlation="no", # change to 'spatial' later perhaps
    maxit=100,  # default
    tol=0.0001 # default
)

fh_simple
```
```{r}
fh_simple$ind
```

```{r}
fh_simple %>% summary()
```

```{r}
lm(est ~ 1, data=simple_df)
```


```{r}
plot(fh_simple)
```

